name: falletter_mobile_v2
description: "This is an anonymous communication community service exclusively for DSM students."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_svg: ^2.1.0
  material_symbols_icons: ^4.2815.0
  intl: ^0.20.2
  lottie: ^3.1.0
  dio: ^5.4.0
  riverpod: ^3.0.3
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: WantedSans
      fonts:
        - asset: assets/fonts/wanted_sans_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/wanted_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/wanted_sans_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/wanted_sans_medium.ttf
          weight: 500
        - asset: assets/fonts/wanted_sans_regular.ttf
          weight: 400

  assets:
    - assets/icon/
    - assets/lottie/