name: falletter_mobile_v2
description: "This is an anonymous communication community service exclusively for DSM students."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_svg: ^2.1.0
  material_symbols_icons: ^4.2815.0
  intl: ^0.20.2
  lottie: ^3.1.0
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  timeago: ^3.7.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/svg/falletter_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: WantedSans
      fonts:
        - asset: assets/font/wanted_sans_extra_bold.ttf
          weight: 800
        - asset: assets/font/wanted_sans_bold.ttf
          weight: 700
        - asset: assets/font/wanted_sans_semi_bold.ttf
          weight: 600
        - asset: assets/font/wanted_sans_medium.ttf
          weight: 500
        - asset: assets/font/wanted_sans_regular.ttf
          weight: 400

  assets:
    - assets/
    - assets/svg/
    - assets/svg/brick/
    - assets/svg/letter/
    - assets/svg/notice/
    - assets/svg/on_boarding/
    - assets/svg/received_letter/
    - assets/svg/roulette_check/
    - assets/svg/theme_mode/
    - assets/lottie/
    - assets/text/